-- Run after schema.sql

INSERT INTO exercises (name, description, muscle_group, equipment, difficulty) VALUES
  ('Bench Press', 'A classic compound exercise for building chest size and strength.', 'Chest', 'Barbell', 'intermediate'),
  ('Incline Bench Press', 'Targets the upper portion of the pectoral muscles.', 'Chest', 'Barbell', 'intermediate'),
  ('Decline Bench Press', 'Focuses on the lower pectoral muscles.', 'Chest', 'Barbell', 'intermediate'),
  ('Push-Up', 'A fundamental bodyweight exercise for the chest, shoulders, and triceps.', 'Chest', 'Bodyweight', 'beginner'),
  ('Cable Fly', 'A machine-based isolation exercise providing constant tension on the chest.', 'Chest', 'Machine', 'intermediate'),
  ('Dumbbell Fly', 'An isolation movement that stretches the chest muscles deeply.', 'Chest', 'Dumbbell', 'intermediate'),
  ('Chest Dip', 'A bodyweight exercise that heavily recruits the lower chest and triceps.', 'Chest', 'Bodyweight', 'advanced'),
  
  ('Deadlift', 'A foundational compound lift targeting the entire posterior chain.', 'Back', 'Barbell', 'advanced'),
  ('Pull-Up', 'The ultimate bodyweight exercise for vertical pulling strength.', 'Back', 'Bodyweight', 'intermediate'),
  ('Lat Pulldown', 'A machine variation of pull-ups focusing on the latissimus dorsi.', 'Back', 'Machine', 'beginner'),
  ('Seated Cable Row', 'A horizontal pulling back machine exercise.', 'Back', 'Machine', 'beginner'),
  ('Bent Over Row', 'A heavy barbell row targeting the mid-back and lats.', 'Back', 'Barbell', 'intermediate'),
  ('T-Bar Row', 'A supported rowing movement for back thickness.', 'Back', 'Machine', 'intermediate'),
  ('Single Arm Dumbbell Row', 'A unilateral row to fix back strength imbalances.', 'Back', 'Dumbbell', 'beginner'),
  ('Face Pull', 'An essential exercise for rear delts and poor posture correction.', 'Back', 'Cable', 'beginner'),

  ('Overhead Press', 'The primary compound lift for building big shoulders.', 'Shoulders', 'Barbell', 'intermediate'),
  ('Arnold Press', 'A seated dumbbell press with rotation to hit all shoulder heads.', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Lateral Raise', 'An isolation exercise specifically for shoulder width (lateral delts).', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Front Raise', 'Focuses entirely on the anterior (front) deltoids.', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Rear Delt Fly', 'Targets the posterior deltoids to complete the 3D shoulder look.', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Upright Row', 'A pulling movement hitting the upper traps and side delts.', 'Shoulders', 'Barbell', 'intermediate'),
  ('Shrug', 'An isolation movement for enormous upper trapezius muscles.', 'Shoulders', 'Dumbbell', 'beginner'),

  ('Barbell Curl', 'The classic mass-builder for the biceps.', 'Arms', 'Barbell', 'beginner'),
  ('Dumbbell Curl', 'Allows independent arm movement for bicep isolation.', 'Arms', 'Dumbbell', 'beginner'),
  ('Hammer Curl', 'Targets the brachialis to push the bicep up, increasing arm thickness.', 'Arms', 'Dumbbell', 'beginner'),
  ('Preacher Curl', 'Strict isolation curl using a padded bench.', 'Arms', 'Barbell', 'intermediate'),
  ('Tricep Pushdown', 'A cable exercise for constant tension on the triceps during extension.', 'Arms', 'Cable', 'beginner'),
  ('Skull Crusher', 'Lying tricep extension for building tricep mass.', 'Arms', 'Barbell', 'intermediate'),
  ('Overhead Tricep Extension', 'Focuses on the long head of the tricep muscle.', 'Arms', 'Dumbbell', 'beginner'),
  ('Close Grip Bench Press', 'A compound press focusing heavily on tricep activation.', 'Arms', 'Barbell', 'intermediate'),
  ('Diamond Push-Up', 'A bodyweight push-up variation focusing on the triceps.', 'Arms', 'Bodyweight', 'beginner'),

  ('Squat', 'The absolute king of lower body exercises for all leg muscles.', 'Legs', 'Barbell', 'intermediate'),
  ('Front Squat', 'A squat variation that shifts focus more to the quadriceps.', 'Legs', 'Barbell', 'advanced'),
  ('Leg Press', 'A machine-based compound leg exercise allowing heavy weights.', 'Legs', 'Machine', 'beginner'),
  ('Romanian Deadlift', 'A hamstring and glute-focused hip hinge movement.', 'Legs', 'Barbell', 'intermediate'),
  ('Leg Curl', 'An isolation movement for the hamstring muscles.', 'Legs', 'Machine', 'beginner'),
  ('Leg Extension', 'An isolation machine movement exclusively for the quadriceps.', 'Legs', 'Machine', 'beginner'),
  ('Calf Raise', 'A straight-leg exercise to build calf size.', 'Legs', 'Machine', 'beginner'),
  ('Hack Squat', 'A machine squat variation that safely supports the back.', 'Legs', 'Machine', 'intermediate'),
  ('Bulgarian Split Squat', 'A brutal unilateral leg exercise for balance and strength.', 'Legs', 'Dumbbell', 'advanced'),
  ('Lunges', 'A functional single-leg movement for quads and glutes.', 'Legs', 'Dumbbell', 'beginner'),

  ('Plank', 'An isometric core hold for total abdominal endurance.', 'Core', 'Bodyweight', 'beginner'),
  ('Crunch', 'A classic contraction for the upper abdominals.', 'Core', 'Bodyweight', 'beginner'),
  ('Sit-Up', 'A full range of motion core exercise.', 'Core', 'Bodyweight', 'beginner'),
  ('Leg Raise', 'A highly effective movement for the lower abdominals.', 'Core', 'Bodyweight', 'intermediate'),
  ('Russian Twist', 'A rotational core exercise focusing on the obliques.', 'Core', 'Bodyweight', 'beginner'),
  ('Cable Crunch', 'Weighted abdominal crunch using a cable machine.', 'Core', 'Cable', 'intermediate'),
  ('Ab Wheel Rollout', 'An advanced anti-extension exercise for incredible core strength.', 'Core', 'Equipment', 'advanced'),

  ('Treadmill Run', 'Steady state or interval running indoors.', 'Cardio', 'Machine', 'beginner'),
  ('Cycling', 'Low impact cardiovascular exercise on a stationary bike.', 'Cardio', 'Machine', 'beginner'),
  ('Rowing Machine', 'A full-body cardiovascular workout targeting the back and legs as well.', 'Cardio', 'Machine', 'intermediate'),
  ('Jump Rope', 'A high-intensity coordination cardio drill.', 'Cardio', 'Rope', 'intermediate'),
  ('Stair Climber', 'Intense low-impact cardio focusing heavily on the lower body.', 'Cardio', 'Machine', 'beginner'),
  ('Burpees', 'A full-body cardiovascular and muscular endurance test.', 'Cardio', 'Bodyweight', 'intermediate'),
  ('Mountain Climbers', 'A high-intensity bodyweight cardio and core exercise.', 'Cardio', 'Bodyweight', 'beginner')
ON CONFLICT (name) DO NOTHING;
